#!/bin/bash

export PACKAGE_CORE_NAME="kubectl"
export PACKAGE_CORE_ORG="kubernetes"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION="v1.29.1"

export PACKAGE_CORE_GIT_REPOSITORY="https://github.com/${PACKAGE_CORE_ORG}/${PACKAGE_CORE_NAME}"

export PACKAGE_CORE_RELEASE_DOWNLOAD="https://dl.k8s.io/release"
